SD = "videos/"
TD = "videos/transcoding/"
DD = "videos/transcoded/"
DebugStart = "00:00:00"
DebugEnd = "00:00:30"
TempJson = "transcode/temp.json"
TempTxt = "transcode/data.json"
VBW = 2500
ABW = 128
DataGen = "transcode/generate_data.py"
LogP = "info.log"